name: KitoScreensExample
options:
  bundleIdPrefix: co.triply
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
packages:
  KitoScreens:
    path: ..
targets:
  KitoScreensExample:
    type: application
    platform: iOS
    sources:
      - Sources
    dependencies:
      - package: KitoScreens
    settings:
      base:
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        CFBundleDisplayName: Kito Screens
